### ISSUE TITLE
Specifies directories to scan for @import directives when parsing.

### ISSUE THREAD

**Issue by rochappy** [stevelacy/gulp-stylus#105]
You can achieve a similar effect it https://github.com/gruntjs/grunt-contrib-stylus, Specifies directories to scan

**Comment by stevelacy** [comment]
I do not plan to add options which will change the behavior of gulp.src and standard stylus imports.

**Comment by jenius** [comment]
I might have totally misinterpreted this, but you can add `@import` directories using the `paths` option if that's what you were asking by any chance too
