### ISSUE TITLE
Order of source files affects @import

### ISSUE THREAD

**Issue by stevekeiser** [stevelacy/gulp-stylus#107]
```coffee
paths = [
	'assets/stylus/fonts.styl'
	'assets/stylus/main.styl'
]

gulp.task 'stylus', ->
	gulp.src(paths)
		.pipe(stylus(
			use: nib()
		))
		.pipe(gulp.dest('public/css/app'))
```

Seeing an issue where main.styl requests `@import 'fonts'` but it doesn't work unless fonts.styl appears after main.styl in the list given to `gulp.src`. It seems like the import should work regardless of the order? In the case were it *doesn't* work, there is no error. Am I doing something wrong?

**Comment by stevekeiser** [comment]
Fixed if I revert Stylus to 0.37.0. I guess this is a Stylus issue, sorry!

**Comment by stevelacy** [comment]
Can you open an issue on stylus to confirm that the version no longer supports that particular order?

**Comment by stevekeiser** [comment]
Yes, I will. Looks like the bug was introduced between .48 and .49

**Comment by stevekeiser** [comment]
This is a known [issue](https://github.com/LearnBoost/stylus/issues/1403) in Stylus. Setting the option ```cache: false``` is a temporary workaround.

**Comment by stevelacy** [comment]
Ah, thanks for the research!
