### ISSUE TITLE
Keep six-digit colors

### ISSUE THREAD

**Issue by ruandre** [stevelacy/gulp-stylus#113]
Stylus converts six-digit colors down to three where possible.
For example: `#00ff00` to `#0f0`

Is there an option I can pass to Stylus to disable this?
I'm trying to keep six-digit colors for HTML emails.

Should I ask at [jenius/accord](https://github.com/jenius/accord) or [LearnBoost/stylus](https://github.com/LearnBoost/stylus) instead?

**Comment by stevelacy** [comment]
Open the issue on [stylus](https://github.com/LearnBoost/stylus).
