### ISSUE TITLE
Text-shadow compiling bug

### ISSUE THREAD

**Issue by alvik48** [stevelacy/gulp-stylus#115]
Hi.

When compiling *.styl* file, I get error on **text-shadow** property. Example:

#####app.styl

    .logo
      text-shadow 1px 1px 2px rgba(#000, .6)

#####app.css

    .logo {
      text-shadow: 1px;
	}

But if I add **,;** in source file or simply add another text-shadow, then first text-shadow will appeared correctly. Example:

#####app.styl

     .logo
       text-shadow 1px 1px 2px rgba(#000, .6),;

#####app.css

     .logo {
       text-shadow: 1px 1px 2px rgba(0,0,0,0.6);
     }

This issue reproduces in repo [https://github.com/alvik48/speed-markup](https://github.com/alvik48/speed-markup), look to **.logo** class.

**Comment by jenius** [comment]
This is a stylus error, you can file it in [the stylus repo](https://github.com/LearnBoost/stylus)
