### ISSUE TITLE
External Sourcemaps write error

### ISSUE THREAD

**Issue by themarkappleby** [stevelacy/gulp-stylus#121]
When attempting to write an external sourcemap, I'm getting the following error: `no writecb in Transform class`. The inline sourcemap appears to be working fine. Please see my related code below:

````
gulp.task('styles', ['clean'], function(){
  return gulp.src(paths.styles.src)
    .pipe(sourcemaps.init())
    .pipe(stylus({
      cache: false,
      compress: true
    }).on('error', notify.onError({
      title: 'Stylus Error',
      message: "\n<%= error.message %>"
    })))
    .pipe(sourcemaps.write('.'))
    .pipe(autoprefixer())
    .pipe(gulp.dest(paths.styles.dest));
});
````

**Comment by stevelacy** [comment]
Remove `autoprefixer`
Add: `gulp` and `gulp-stylus` version

**Comment by themarkappleby** [comment]
Swapping the order of `.pipe(autoprefixer())` with `pipe(sourcemaps.write('.'))` seems to have fixed the problem. Thanks.

`gulp -v 3.8.11`
`gulp-stylus 2.0.1`
