### ISSUE TITLE
Recompile on import changes

### ISSUE THREAD

**Issue by wejrowski** [stevelacy/gulp-stylus#125]
I may be missing something, but is there a way to have files recompile when imports are changed?

What I'm using:
```
        watch({glob: "src/**/*.styl"}, function(files) {
            return files
                .pipe(stylus({use: [nib()]}))
                .pipe(gulp.dest("./src"));
        });

```

**Comment by stevelacy** [comment]
Add the imported files to the watch array.

**Comment by wejrowski** [comment]
Where do you mean?

**Comment by stevelacy** [comment]
What are your `@imports`, are they local files in the filesystem?
If so just add them to your watch:

```js
gulp.task('css', function() {
  gulp.src('./src**/*.styl')
    .pipe(stylus({use: [nib()]}))
    .pipe(gulp.dest('./src'));
});

gulp.watch(['./**.css', './**.styl'], ['css']);

```

I would suggest using `gulp-cached` to ensure the files are only updated on change.

**Comment by codeyash** [comment]
There is main file inventive.styl which contains all imports. When internal imported files changed function stylus triggers but main inventive.styl don't get compiled and internal does like nav,styl. Am I doing wrong or missing?  

   gulp.task('stylus', function () {

        var filter = Filter('**/*.styl');

        return gulp.src(
        [   
            './src/stylus/inventive.styl',
            './src/stylus/*.styl',
            './src/stylus/**/*.styl',
            '!./src/stylus/**/_*.styl'
        ], { base: 'src/stylus' }
        )
        .pipe(cached('build'))
        .pipe(filter)
        .pipe(stylus({error: true, use: [nib()]}))
        .pipe(filter.restore())
        .pipe(gulp.dest('./build/css'))
        .pipe(browserSync.stream())
        ;
     });



    // configure which files to watch and what tasks to use on file changes
    gulp.task('watch', function() {
    
      gulp.watch(['src/stylus/**/*.styl','build/css/**/*.css'], ['stylus']);
  
    });


Full file : https://github.com/speedovation/Inventive/blob/master/gulpfile.js
