### ISSUE TITLE
Issue with transitions

### ISSUE THREAD

**Issue by maartendraijer** [stevelacy/gulp-stylus#126]
Not sure if I'm submitting this issue to the right repository, but I'm having an issue with `transition all .3s` being compiled to `_transition: all 3s;`. This is my gulp task:

```js
gulp.task('stylus', function() {
    return gulp.src(config.destPath + 'css/app.styl')
        .pipe(plumber({
            errorHandler: onError
        }))
        .pipe(stylus({
            use: [jeet()]
        }))
        .pipe(gulp.dest(config.destPath + 'css/'))
        .pipe(reload({ stream: true }));
});
```

Anyone else experiencing the same problem or knowing how to fix?

**Comment by stevelacy** [comment]
Please open stylus related issues on the stylus repo: https://github.com/learnboost/stylus

You can add your styl file here as it might just be a small fix to your styl code if I notice the bug.

**Comment by maartendraijer** [comment]
@stevelacy Thanks for your reply. I'm literally using:

```stylus
.button
  transition all .3s
  background-color #999

  &:hover
    background-color #333
```

**Comment by stevelacy** [comment]
Use the stylus CLI to confirm that the output is different.
Add:
- `stylus` version
- `gulp-stylus` version

I created a test repo to reproduce the issue: https://github.com/stevelacy/gulp-stylus-126
The code is parsed correctly, try to reproduce it and create a test repo as well.

**Comment by maartendraijer** [comment]
It is fixed already, see https://github.com/jenius/axis/issues/179.

**Comment by jenius** [comment]
:+1:
