### ISSUE TITLE
Potentially unhandled rejection [2] Error: no writecb 

### ISSUE THREAD

**Issue by Penagwin** [stevelacy/gulp-stylus#129]
Full Error: 
    `Potentially unhandled rejection [2] Error: no writecb in Transform class`

This issue has occurred here : https://github.com/stevelacy/gulp-stylus/issues/127

I believe that some form of a fix needs to be applied to gulp-stylus.
Both gulp-traceur: https://github.com/sindresorhus/gulp-traceur/pull/42
and gulp-esnext: https://github.com/sindresorhus/gulp-esnext/issues/8
have applied changes to fix the issue.

The fix appears to be small, requiring very few changes. I attempted to fix the issue and was unable to make it work.

Thank you!

**Comment by Penagwin** [comment]
Some stupid mistake I made, sorry.

**Comment by SachaG** [comment]
I'm running into the same thing, I'd be curious to know how you fixed it?

**Comment by SachaG** [comment]
Oh, well that was easy. Upgrading Node to the latest version fixed it (in fact I had tried that already but for some reason Gulp was still running using an older version).

**Comment by NikosEfthias** [comment]
well i am using the latest node already but nothing fixes this we can simply say that gulp is broken
