### ISSUE TITLE
Do not output source file contents on error

### ISSUE THREAD

**Issue by zenwarr** [stevelacy/gulp-stylus#132]
When there is error in .styl file, gulp prints entire source file contents to console after stack trace. It makes impossible to see the error message itself, as source file can be very long and Windows console has limit of lines that can be shown on screen.
gulp-stylus should prevent gulp-util from showing .input property of error object.

**Comment by stevelacy** [comment]
Please show an example of the current output compared to your proposed output.

For me the output error prints only the lines in question creating the error.

**Comment by zenwarr** [comment]
I'm sorry for not providing enough information.
This behaviour only exists when using gulp-plumber to report about errors. gulp-plumber uses gulp-util.PluginError.toString function to display information about exception, and gulp-util simply iterates over all available and not blacklisted props of error object, so it is not plumber or gulp-util issue.
Additionally, stylus adds input property to error object only in some cases (for example, when @import fails to find file requested).
You can see example of such output in demo project: https://github.com/zenwarr/gulp-stylus-plumber
Console output without gulp-plumber: https://github.com/zenwarr/gulp-stylus-plumber/blob/master/without-plumber.log
Console output with gulp-plumber: https://github.com/zenwarr/gulp-stylus-plumber/blob/master/with-plumber.log
Console output with gulp-plumber enabled and suggested fix to gulp-stylus: https://github.com/zenwarr/gulp-stylus-plumber/blob/master/with-fix.log

**Comment by stevelacy** [comment]
Thanks for the explanation, merging
