### ISSUE TITLE
Using the hoist-atrules option

### ISSUE THREAD

**Issue by futekov** [stevelacy/gulp-stylus#134]
Hi, I can't figure out how to pass some options like [`hoist-atrules`](https://learnboost.github.io/stylus/docs/executable.html) to Stylus in my gulpfile, putting them in `set` doesn't work either.

**Comment by jenius** [comment]
Did you try quoting them as a string with a space and passing them to `set`? Like `hoist atrules`? Stylus has some very strange option parsing. We'd need to find out how that particular options is parsed in the API rather than the executable in order to know for sure.

**Comment by futekov** [comment]
Passing it to the plugin as `hoist atrules` did work, thanks. However, it didn't work when passed to `set`.
Previously I was testing with `hoist-atrules` and `hoistAtrules`, neither of which worked.

Thanks :)

**Comment by jenius** [comment]
Ah yeah sorry that was what I was thinking in my brain and didn't type it haha. Really glad this ended up working, and apologies for stylus' super weird options handling, it hangs a lot of people up :confused:
