### ISSUE TITLE
Stylus dependency

### ISSUE THREAD

**Issue by cakeinpanic** [stevelacy/gulp-stylus#135]
Hello!
In my project i uses `gulp-stylus` and `stylus` by itself.
package.json:

```
"dependencies": {
    "gulp-stylus": "^2.0.5",
    "stylus": "^0.51.1"
  }
```

So `gulp-stylus` doesn't install its own copy of `stylus` (i guess it's because of `*` in your package.json)
And then i get
`Error: Cannot find module 'gulp-stylus/node_modules/stylus'
`

**Comment by stevelacy** [comment]
What version of npm and gulp are you using?
I created a test repo which installs and seems to run correctly with the info you provided:

https://github.com/stevelacy/gulp-stylus-135
npm:  2.10.1

**Comment by neochrome** [comment]
Stylus just got bumped to `0.52.1` and broke `gulp-stylus` for me.

Maybe it would be a good idea to lock down to a specific version of stylus in order to get predictable builds? Say `0.52.0`, which works when reverted to locally.

Please see https://github.com/stylus/stylus/issues/1996
and https://github.com/tj/nib/issues/315 for further info.

**Comment by drewloomer** [comment]
There should be a patch coming today. Until then you can simply `npm install stylus@0.52.0` from inside of gulp-stylus.

**Comment by neochrome** [comment]
Yep that works locally, but not so well on the build server. I guess I could resort to shrink-wrapping everything to fully manage all deps myself.

I appreciate that it's a tough choice whether to have explicit or loose dependencies. Both has their pros and cons. It's just that it gets a little bit unpredictable when they change between two builds :)

**Comment by neochrome** [comment]
btw, do you know how I can have the gulp-task fail when an error like that happens?

relevant task:
```
gulp.task('minify:css', function () {
  return gulp.src('./client/index.styl')
    .pipe(sourcemaps.init({ loadMaps: true }))
      .pipe(stylus({
        'resolve url': true,                         
        'use'        : nib(),
        'import'     : 'nib',
        'url'        : 'embedurl'
      }))
      .pipe(minifycss({ 'keepSpecialComments': 0 }))
    .pipe(rename('index.min.css'))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('./client/'))
    .pipe(livereload());
});
```

**Comment by neochrome** [comment]
btw, do you know how I can have the gulp-task fail when an error like that happens?

relevant task:
```
gulp.task('minify:css', function () {
  return gulp.src('./client/index.styl')
    .pipe(sourcemaps.init({ loadMaps: true }))
      .pipe(stylus({
        'resolve url': true,                         
        'use'        : nib(),
        'import'     : 'nib',
        'url'        : 'embedurl'
      }))
      .pipe(minifycss({ 'keepSpecialComments': 0 }))
    .pipe(rename('index.min.css'))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('./client/'))
    .pipe(livereload());
});
```

**Comment by drewloomer** [comment]
I believe doing something like
`
gulp.task('minify:css', function () {
  return gulp.src('./client/index.styl')
    .on('error', function(err) {
        console.log(err.toString());
        this.emit('end');
    })
    .pipe(sourcemaps.init({ loadMaps: true }))
      .pipe(stylus({
        'resolve url': true,                         
        'use'        : nib(),
        'import'     : 'nib',
        'url'        : 'embedurl'
      }))
      .pipe(minifycss({ 'keepSpecialComments': 0 }))
    .pipe(rename('index.min.css'))
    .pipe(sourcemaps.write('./'))
    .pipe(gulp.dest('./client/'))
    .pipe(livereload());
});
`
would do the trick. `this.emit('end')` might need to be `process.exit(1);` but I just can't remember. Perhaps either would work.

**Comment by neochrome** [comment]
Thanks!
Got it to work once I hooked `.on('error', ....)` right after the stylus pipe.
Also, I detect if the task is run as part of a build or when watching changes and then use `process.exit(1)` or `this.emit('end')` to either fail or just end the task early.

**Comment by elvinzhu** [comment]
Great job, thanks!
Now it will output nothing when parse error happens and the css files stay the save as before. In this case, i cannot get notified immediately. 
It's nicer to output error message to the html pages via `body:beore` like gulp-ruby-sass does .
