### ISSUE TITLE
expose define

### ISSUE THREAD

**Issue by contra** [stevelacy/gulp-stylus#138]
allow users to define stuff via props

https://learnboost.github.io/stylus/docs/functions.url.html

desired usage

```js
var gstylus = require('gulp-stylus');
var stylus = require('stylus');

gstylus({
  define: {
    url: stylus.url()
  }
})
```

**Comment by stevelacy** [comment]
Already exposed in accord's options layer:
https://github.com/jenius/accord/blob/master/docs/stylus.md#define

**Comment by contra** [comment]
perfect
