### ISSUE TITLE
TypeError: undefined is not a function

### ISSUE THREAD

**Issue by eskhool** [stevelacy/gulp-stylus#142]
I'm getting this error while compiling any styl file with the following context

/mnt/code/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623
    var written = dest.write(chunk);
                       ^
TypeError: undefined is not a function
  at write (/mnt/code/node_modules/gulp-sourcemaps/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:623:24)

npm 2.12.1
gulp-stylus 2.0.6
stylus 0.52.4

**Comment by stevelacy** [comment]
Not related to this plugin - `gulp-sourcemaps`

**Comment by eskhool** [comment]
I disable gulp-sourcemaps and the error remains.

  at node.js:814:3

/mnt/code/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523
    dest.end();
         ^
TypeError: undefined is not a function

**Comment by stevelacy** [comment]
Not related to this plugin. Please read the error message.

`/mnt/code/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523`

**Comment by eskhool** [comment]
@stevelacy, I did read the message but this is a plugin that gulp itself depends on and both gulp-jade and gulp-coffee plugins work fine with it. Here is how I am invoking the plugin, that too with a single file. 

  gulp.task('stylus', function() {
    gulp.src('www/**/*.styl').pipe(stylus()).pipe(gulp.dest('www/'));
  });
