### ISSUE TITLE
TypeError: undefined is not a function 

### ISSUE THREAD

**Issue by eskhool** [stevelacy/gulp-stylus#143]
I'm getting this error while compiling any styl file with the following context

I disable gulp-sourcemaps and the error remains.

at node.js:814:3

/mnt/code/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523
dest.end();
^
TypeError: undefined is not a function

npm 2.12.1
gulp-stylus 2.0.6
stylus 0.52.4

**Comment by stevelacy** [comment]
As #142 
Not related to this plugin.

`/mnt/code/node_modules/gulp/node_modules/vinyl-fs/node_modules/through2/node_modules/readable-stream/lib/_stream_readable.js:523`

Closed
