### ISSUE TITLE
stylus sourcemap cut off

### ISSUE THREAD

**Issue by Keksinautin** [stevelacy/gulp-stylus#147]
Hi. I used `gulp-stylus` and tried to generate inline source-map. 

``` javascript
.pipe(gulpStylus({
    sourcemap: { inline: true }
}))
```

But I could not understand why I could not find source-map in a result file.
When I used CLI `stylus src.styl -o out --sourcemap-inline` it worked good. 
Then I found this string:

``` javascript
res.result = res.result.replace(/^\s*\/\*[@#][\s\t]+sourceMappingURL=.*$/mg, '');
```

https://github.com/stevelacy/gulp-stylus/blob/master/index.js#L37

and I don't understand why your are cutting the stylus-generated source-map off.
What is it for?
If it is a feature may be it will be good to tell about it in the readme?

**Comment by stevelacy** [comment]
Look at the README.md where it shows the sourcemap example. You do not need to set the sourcemap parameter, use `gulp-sourcemaps`

**Comment by Keksinautin** [comment]
Yes, I looked. But there are cases when it can not work. I pass only one file to input and use imports to include my another files and external dependencies. `gulp-sourcemaps` knows nothing about them, so only stylus can make full source-map of all my files. And it works fine, when I use CLI. 
I think if you limit functional of the thing that you provide through you plugin, it is better to say about it.
So, could you explain what is the purpose of cutting off stylus source-map in your plugin, please? I had to make a fork for solving my case, but of course it is not very convenient. I am trying to understand your motivation in this feature, may be then we can find compromise.
