### ISSUE TITLE
npm3 support

### ISSUE THREAD

**Issue by klausbayrhammer** [stevelacy/gulp-stylus#148]
Hi,
Since we've switched to npm3 and we had a couple of problems with relative imports in our stylus files.

Given to following dependencies
```
    "gulp": "^3.9.0",
    "gulp-stylus": "^2.1.0",
    "stylus": "^0.49.3"
```
and the following folder structure
```
stylus_files_1/
| index.styl
| variables.styl
stylus_files_2/
| emptyRequireInOtherFolder.styl
| variables.styl
gulpfile.js
```

When you do the following `require`'s and `import`'s in the index.styl
```
@require "emptyRequireInOtherFolder.styl"
@import "./variables.styl"
```
we get a different result when we run the task with npm2 and npm3. When using npm2 the `stylus_files_1/variables.styl` is imported (as expected). When using npm3 `stylus_files_2/variables.styl` is used.

You can use the [klausbayrhammer/gulp-stylus-accord](https://github.com/klausbayrhammer/gulp-stylus-accord) to reproduce the problem.

ps: The problem doesn't occur when using stylus 0.52.4, but with npm3 `require('accord').load('stylus')` seem to load the stylus dependency in the root node_modules directory rather than the stylus dependency specified in gulp. @jenius could this probably be an accord issue?

**Comment by stevelacy** [comment]
I am not following this correctly - but from what I could gather, you have an issue with `stylus@0.4x` which is not supported by gulp-stylus.

`require` is not related to npm, but node. `require('accord').load('stylus')` will always require stylus from the `node_modules/stylus` folder

Use stylus@0.5x.

**Comment by klausbayrhammer** [comment]
Did you try to reproduce it with [klausbayrhammer/gulp-stylus-accord](https://github.com/klausbayrhammer/gulp-stylus-accord)?

When installing the project with npm2 the node_modules look like this:

```
node_modules
   |-gulp-stylus
   |---node_modules
   |-----accord
   |-----stylus (0.50.x)
   |-stylus (0.49.x)
```
In this case I expect `require('accord').load('stylus')` to pick up `stylus@0.50.x` since accord and stylus@0.50.x are in the same node_modules.

With npm3 it looks like this
```
node_modules
   |-accord
   |-gulp-stylus
   |---node_modules
   |-----stylus (0.50.x)
   |-stylus (0.49.x)
```

 With the npm3's dependency layout seems as if accord picks up stylus@0.49.x because they are both in the root node_modules (although I'd want accord to pick up stylus@0.50.x which is in gulp-stylus' node_modules)

**Comment by stevelacy** [comment]
Any updates from the other issue, or should I close?

**Comment by klausbayrhammer** [comment]
Although this gives me the creeps, I don't think it's an issue that can be fixed in the gulp-stylus plugin itself. And since the problem and a workaround is documented in this issue its ok for me to close it.
