### ISSUE TITLE
stylus .define raw functionality not being passed thorugh

### ISSUE THREAD

**Issue by acidjazz** [stevelacy/gulp-stylus#151]
I believe this is something in accord, I've attempted to fix it here

https://github.com/jenius/accord/pull/122

This is just to help track the fix in case I'm wrong.

Reference:
https://github.com/stylus/stylus/issues/1286#issuecomment-38357359
https://github.com/gruntjs/grunt-contrib-stylus/issues/100

**Comment by stevelacy** [comment]
Sounds good, let me know when to update the deps @jenius

**Comment by acidjazz** [comment]
Thanks! merge accepted

https://github.com/jenius/accord/pull/122

I'll let ya know as soon as a version comes out so we can update your package.json and close this up!

**Comment by acidjazz** [comment]
released! I'll issue a pull for you or you can change it yourself if ya want.

https://github.com/jenius/accord/releases/tag/v0.20.5

**Comment by jkarttunen** [comment]
Would be nice to have an example in readme about doing this.

**Comment by acidjazz** [comment]
[not](https://github.com/stevelacy/gulp-stylus/pull/171) a problem @jkarttunen
