### ISSUE TITLE
eos error on @keyframe definition

### ISSUE THREAD

**Issue by nathanhornby** [stevelacy/gulp-stylus#153]
```
@keyframes arrow-bounce {
  0% {
    top: 13px;
  40% {
    top: 17px;
  }
  80% {
    top: 15px;
  }
  100% {
    top: 13px;
  }
}
```

Is giving me:

```
   89|   100% {
   90|     top: 13px;
   91|   }
   92| }
   93|
-------^

unexpected "eos"
```

Any ideas?

**Comment by nathanhornby** [comment]
Hm, it seems removing the braces fixed the error, but this is unexpected according to the docs which state:

> Stylus supports @keyframes both with curly braces or without them

Is this an issue I should raise in the Stylus repo?

**Comment by stevelacy** [comment]
Stylus repo
