### ISSUE TITLE
Update stylus to 0.53.0

### ISSUE THREAD

**Issue by Jokero** [stevelacy/gulp-stylus#154]
Some cool features were released:
* [Numeric partial references](http://stylus-lang.com/docs/selectors.html#partial-reference)
* [Relative references](http://stylus-lang.com/docs/selectors.html#relative-reference)

**Comment by stevelacy** [comment]
added and published to v2.1.2 :)

https://github.com/stevelacy/gulp-stylus/releases/tag/2.1.2

**Comment by Jokero** [comment]
Thanks! It's very fast :smiley:
