### ISSUE TITLE
Update examples

### ISSUE THREAD

**Issue by iDev0urer** [stevelacy/gulp-stylus#155]
It looks as though the examples haven't been updated in a while. Right now all of the files look about the same

**Comment by stevelacy** [comment]
This is the only example which matters: https://github.com/stevelacy/gulp-stylus/blob/master/examples/gulpfile.js

I can delete the stylus files as this project is a plugin, not the main stylus repo.

**Comment by jkarttunen** [comment]
Would be nice to have example of passing arguments.

**Comment by stevelacy** [comment]
All arguments have examples:
https://github.com/stevelacy/gulp-stylus/blob/master/README.md

**Comment by jkarttunen** [comment]
I guess i was looking for this (passing locals to Accord and to be used in stylus files:

in gulpfule.js: 
```
pipe(stylus({define:{'fontFace' : 'FranklinGothic'}}))
```
and then in index.styl:
```
  if fontFace == Roboto
    font-family: Roboto, sans-serif
  else if fontFace == FranklinGothic
    font-family: FranklinGothicURWCon-Dem, sans-serif
```

The pieces are there but having it visible can save a few hours of trial and error
