### ISSUE TITLE
Is there a way to import files to certain stylus files by default?

### ISSUE THREAD

**Issue by evilgeniuscreative** [stevelacy/gulp-stylus#156]
Is there a way to import certain files, say, colors.styl at the head of each .styl file? This is in grunt-contrib-stylus (https://github.com/gruntjs/grunt-contrib-stylus#import) wondering if that's a part of this as well? If not, it'd be great to have!

**Comment by stevelacy** [comment]
https://github.com/jenius/accord/blob/master/docs/stylus.md#import

**Comment by evilgeniuscreative** [comment]
Thank you, sir!

**Comment by evilgeniuscreative** [comment]
Actually, Steve, sorry, now I'm confused. I'm new to Gulp. I'm using gulp-stylus. Do I also need to load accord to do this or can I do it through gulp-stylus?

Where would it fit in  here?

    gulp.task( 'compileStylus', function () {
        return gulp.src( 'src/css/styles.styl' )
            .pipe( stylus( {
                                  linenos      : true,
                                  'include css': true,
                                  set: ['resolve url']
                              } ) )
            .pipe( gulp.dest( 'dist/css' ) )
    } );

**Comment by stevelacy** [comment]
through gulp-stylus
