### ISSUE TITLE
How to pass locals/globals?

### ISSUE THREAD

**Issue by jkarttunen** [stevelacy/gulp-stylus#159]
I've been struggling with this for way too long. How to pass global variables to stylus?

(as in 'stylus.define({'themeColor','#FF00FF'}

**Comment by stevelacy** [comment]
https://github.com/jenius/accord/blob/master/docs/stylus.md#define

**Comment by jkarttunen** [comment]
Got it. For anyone looking at this:

Update to gulp-stylus 2.3.x
and do
`  .pipe(stylus({define:{'themeColor':'#fff'}}))? `
