### ISSUE TITLE
Sourcemaps not work properly

### ISSUE THREAD

**Issue by romanlex** [stevelacy/gulp-stylus#160]
```javascript
gulp.task('style_stylus:build', function() {
    return gulp.src(path.src.style.stylus)
        .pipe(plumber())
        .pipe(sourcemaps.init())
        .pipe(stylus())
        .pipe(autoprefixer(AUTOPREFIXER_BROWSERS))
        .pipe(csscomb())
        .pipe(gulp.dest(path.build.css))
        .pipe(rename({suffix: '.min'}))
        .pipe(nano({zindex: false, mergeRules: false}))
        .pipe(sourcemaps.write('./', {
            includeContent: false,
            sourceRoot: '/src/style/stylus'
        }))
        .pipe(gulp.dest(path.build.css))
        .pipe(plumber.stop())
        .pipe(reload({stream: true, match: '**/*.css'}))
        .pipe(notify({ title: '[Gulp] CSS Build', message: 'Stylus task complete', onLast: true, wait: false }));
});
```
Sourcemaps not work properly ( What i'm doing wrong? 
I see app.min.css, app.styl and another.
![screenshot_2016-01-30_03-24-19](https://cloud.githubusercontent.com/assets/3369304/12691859/3443e02a-c701-11e5-93e5-85787f2d943a.png)
My dirs:
![screenshot_2016-01-30_03-27-17](https://cloud.githubusercontent.com/assets/3369304/12691879/622cda46-c701-11e5-9816-e7fed29d7a3a.png)
If I use this command and run stylus from CLI:
``` node stylus ../../../src/style/stylus/app.styl -m --compress```
I have properly worked sourcemaps!
![screenshot_2016-01-30_03-41-09](https://cloud.githubusercontent.com/assets/3369304/12692048/511ccc00-c703-11e5-9940-ed4f02539655.png)

**Comment by stevelacy** [comment]
Check the other plugins which modify the stylus

**Comment by romanlex** [comment]
@stevelacy 
Thx, I found what plugin **gulp-cssnano** change css map and add in source array
`"sources":["partials/font.styl",**"app.min.css"**,`
if I remove app.min.css - work properly

Can I save with gulp-stylus uncompressed and comressed css file in destination folder?
