### ISSUE TITLE
Support --resolve-url-nocheck

### ISSUE THREAD

**Issue by thybzi** [stevelacy/gulp-stylus#161]
In #20, `resolve url` support has been added.

Please support both `--resolve-url` and `--resolve-url-nocheck`

Using plain `--resolve-url` may sometimes cause problems, see: https://github.com/stylus/stylus/issues/2119

And that is my related pull request for `grunt-contrib-stylus`, may it help you: https://github.com/gruntjs/grunt-contrib-stylus/pull/147

**Comment by jenius** [comment]
The option as you added it directly to the grunt plugin is already supported and looks like this into gulp-stylus:

```js
{ set: ['resolve url nocheck'] }
```

**Comment by thybzi** [comment]
Thank you! So, everything is already done :)
