### ISSUE TITLE
Pulls in babel-core b/c of accord

### ISSUE THREAD

**Issue by jkrems** [stevelacy/gulp-stylus#167]
Would it be okay to change this module to use stylus directly? `accord` pulls in all of `babel-core` in the latest version. Which seems kind of awkward for a simple "expose stylus for gulp" wrapper.

Happy to write up a PR if that would be okay.

**Comment by jenius** [comment]
Hey, sorry accord should not be pulling babel-core, this should be a dev dependency, that's a bug. I'll switch this over and release now!

**Comment by jkrems** [comment]
Confirmed! `babel-core` vanished in the latest shrinkwrap. Thanks for the quick fix! :)

**Comment by jenius** [comment]
No problem, sorry about the fact that it was in there in the first place!
