### ISSUE TITLE
Error: Cannot find module 'stylus' with stylus 0.54.1

### ISSUE THREAD

**Issue by danteoh** [stevelacy/gulp-stylus#168]
The default npm install of gulp-stylus now includes stylus 0.54.1.  This is breaking gulp-stylus require (in at least node 4.0.0 which I tested this on).

Suggest locking 0.54.0 in 2.3.1 for now.

**Comment by eddiemonge** [comment]
Looks like 0.54.1 was unpublished so you should be good

**Comment by danteoh** [comment]
@stevelacy  sooooo with 0.54.2 published, the same error is happening now...

https://www.npmjs.com/package/stylus shows .2 was published.

**Comment by eddiemonge** [comment]
@danteoh what exactly are you seeing? did you do `npm update`?
