### ISSUE TITLE
Variable + string interpolation or concatenation inside background-image url()

### ISSUE THREAD

**Issue by gusaiani** [stevelacy/gulp-stylus#172]
Hi @stevelacy and all,

been trying to do

```
image-base-url = 'http://domain.com/images/'
body
    background-image url({image-base-url + 'image.png'})
```

and variations of that, so I can interpolate or concatenate the url.

Is that possible? If so, how do I do it?

Many thanks,
Gus

**Comment by stevelacy** [comment]
Please ask this on the stylus project: https://github.com/stylus/stylus
Or read the stylus docs: http://stylus-lang.com/docs/interpolation.html

**Comment by gusaiani** [comment]
Thanks!
