### ISSUE TITLE
Problem in built-in functions with another built-in function

### ISSUE THREAD

**Issue by andersonaguiar** [stevelacy/gulp-stylus#179]
I have this example:

background rgba(green(#f0f), 0.5)

The same problem happens if I put a variable in the place of built-in function.

This generate the error:

   48|       background rgba(green(#f0f), 0.5)
---------------------------------------------^

TypeError: expected rgba or hsla, but got unit:0

Any idea?

**Comment by stevelacy** [comment]
check on [stylus](https://github.com/stylus/stylus)

**Comment by andersonaguiar** [comment]
Can help me?

https://github.com/stylus/stylus/issues/2206
