### ISSUE TITLE
problem with calc(100% + ...)

### ISSUE THREAD

**Issue by scoutrul** [stevelacy/gulp-stylus#193]
Hey, i found a bag with calc() function in :after element.
I tryed to compile this 
`&:after
	max-width: calc(100% - 0.16rem);`
but got error: 
> TypeError: expected string, ident or literal, but got unit:100%

**And i found a solution:**
`	max-width: calc('100% - 0.16rem')`

**Comment by stevelacy** [comment]
This issue should be opened on the stylus main repo, not this project
