### ISSUE TITLE
Why do I need curly braced in my stylus? 

### ISSUE THREAD

**Issue by zfrenchee** [stevelacy/gulp-stylus#194]
Hello, 

I'm working on a new project, and I'm trying gulp instead of grunt. I have a stylus file:
```
.logo
  height 60px
```
And a gulpfile: 
```
gulp.task('styles', function() {
  return gulp.src(paths.stylus + '/*.styl')
    .pipe(stylus())
    .pipe(gulp.dest(paths.css));
});
```
Now, my css file is empty, but when I change my stylus file to:
```
.logo {
  height 60px
}
```
Then I get a css file with
```
.logo {
  height: 60px;
}
```
Which is strange, because you shouldn't need curly braces in stylus. Is this a bug in the plugin? Am I using it wrong? 

Thanks!

**Comment by stevelacy** [comment]
This is a pass through plugin to the stylus project, you do not need braces for stylus.

**Comment by zfrenchee** [comment]
@stevelacy so you're suggesting that the stylus package is causing this odd behavior, not gulp-stylus. Could this have to do with a versioning issue, i.e. which version of stylus gulp-stylus points to? If not, where should I look for where this is coming from?

**Comment by zfrenchee** [comment]
It seems like the last time the tests were run via Travis was last year (9 months ago). I'm not sure how to run them myself, but it might be worth just running them again for a sanity check.

**Comment by stevelacy** [comment]
not needed - stylus has not updated in over a year https://www.npmjs.com/package/stylus

**Comment by zfrenchee** [comment]
@stevelacy I think I've solved this. I was using 2-space indents. I switched to 4-space indents and now it works. I'm confused about it but oh well..
