### ISSUE TITLE
A way to ommit prefix class for component status

### ISSUE THREAD

**Issue by phun-ky** [stevelacy/gulp-stylus#197]
I want to folllow the CSS style guide that Medium has: https://gist.github.com/cuibonobo/16f555c0047ab80044cf, with:

```css
.componentName
  background blue

.componentName.is-stateOfComponent
  background red
```

And then compile them with `gulp-stylus` and this config:

    gulp
      .src('./src/component.styl')
      .pipe(
        stylus({
          prefix: 'foo-',
          include: [
            ...
          ]
        })
      )....

Resulting in:

```css
.foo-componentName
  background: blue;

.foo-componentName.is-stateOfComponent
  background: red;
```

Now it's:

```css
.foo-componentName
  background: blue;

.foo-componentName.foo-is-stateOfComponent
  background: red;
```

Resulting in a lot of extra bytes..

Is this possible? I have hundreds of selectors, so the `prefix` option is nice to have, but I want to ommit class states/or other helper classes from the compiler.

ref: https://github.com/stylus/stylus/issues/2406#issuecomment-409109935

**Comment by stevelacy** [comment]
Not in gulp-stylus, maybe if they answer the question in that issue on stylus
