### ISSUE TITLE
Stylus can't find file @require'd from node_modules

### ISSUE THREAD

**Issue by phun-ky** [stevelacy/gulp-stylus#200]
I have several stylus files, and they have some dependencies in node modules. The requirement is that the stylus files are to be consumed by gulp and webpack. Using these setup:

```stylus
@require '~@guybrush/color/src/color-variables.styl'
```
Yields:

```
failed to locate @require file ~@guybrush/color/src/color-variables.styl
```
With gulp-stylus

Removing the tilde fixes it, but then it breaks webpack..

**Comment by stevelacy** [comment]
I do not handle any of the stylus paths or inclusions, all options are passed directly to stylus. Check to see if they have had this issue, or rather the issue could be with webpack
