### ISSUE TITLE
Error: 'tried to require: stylus'.

### ISSUE THREAD

**Issue by iandrc** [stevelacy/gulp-stylus#201]
Hey 

I'm working with some legacy code, and it uses `gulp-stylus`. I tried all the stuff you and other guys recommended in [#198](https://github.com/stevelacy/gulp-stylus/issues/198) although it didn't help. 

- I installed `stylus` alongside `gulp-stylus`
- I updated Node.js version to the latest available for my project (mainly, `6.17.1`)

What would you suggest?

Node version: `6.17.1`
gulp-stylus version: `2.0.0`
OS: `Windows 10`

**Comment by stevelacy** [comment]
What does your output for npm ls | grep stylus look like?

**Comment by iandrc** [comment]
Fixed it by switching to gulp-stylus `2.1.0`.

Thanks :)
