### ISSUE TITLE
How use nib in gulp-stylus

### ISSUE THREAD

**Issue by desenmeng** [stevelacy/gulp-stylus#47]
```
gulp.task('nib', function(){
    gulp.src('./nib/nib.styl')
        .pipe(stylus({use:[],compress: true}))
        .pipe(gulp.dest('./bulid'));
});
```

> I got this css ,  linear-gradient was not converted

```

#back-to-top {
    fixed: bottom right
}

body {
    background: linear-gradient(top, #fff, #000)
}
```

**Comment by robinfhu** [comment]
I managed to get it working as follows:

     var nib = require('nib');

     gulp.src('./file.styl')
       .pipe(stylus({ use: nib(),  import: ['nib']})
       .pipe(gulp.dest('./out'));

Didn't need to add an ```@import``` to my files

**Comment by computersarecool** [comment]
Is there a way we can add the definitive way to use Nib to the documentation somehow?  Nib is often used with stylus and I don't see anywhere, except in this issue, where this is documented.

**Comment by stevelacy** [comment]
https://github.com/jescalan/accord/blob/master/docs/stylus.md

**Comment by computersarecool** [comment]
So the documentation for accord is the best place to find out how to use Nib in gulp-stylus? I don't mean to be sarcastic, I was just wondering if it would be a good idea to integrated the gulp-stylus documentation.

**Comment by stevelacy** [comment]
That would be duplicating the same documentation as accord/stylus, currently there is a link to the docs in the gulp-stylus readme.

**Comment by computersarecool** [comment]
Ah, gotcha.  thanks
