### ISSUE TITLE
unexpected "eos"

### ISSUE THREAD

**Issue by binarykitchen** [stevelacy/gulp-stylus#55]
```
[16:12:55] Starting 'stylus'...
Potentially unhandled rejection [2] ParseError: /home/michael.heuberger/binarykitchen/code/videomail.io/src/assets/styl/imports/pages/home.styl:112
   108| 
   109| form#email
   110|     display  inline-block
   111|     position relative
 > 112| 

unexpected "eos"
```

Hmmm, what's wrong here? The stylus code looks right to me.

**Comment by wanghuaDev** [comment]
I have the same error，But I don't know how to solve
for $i in  1...{$columns} {
        {$epm-wrapping-class}.col-{$breakpoint}-{$i} {
          make-col($i, $columns, $gutter);
        }
      }
