### ISSUE TITLE
Support for gulp-sourcemaps

### ISSUE THREAD

**Issue by leepowellcouk** [stevelacy/gulp-stylus#70]
... would be great.
https://github.com/floridoo/gulp-sourcemaps

**Comment by jenius** [comment]
Good news guys, I just finished implementing this and it works gloriously. Both inline and external sourcemaps are looking great. I'd expect this feature to ship out today. Whoo! :tada: :confetti_ball:

**Comment by stevelacy** [comment]
:+1:
