### ISSUE TITLE
Can't import css files

### ISSUE THREAD

**Issue by kopax** [stevelacy/gulp-stylus#95]
Hi,

I have lots of trouble to import css files with stylus.
Most of the node_modules i made now require to be in stylus overwise i can't import them with gulp-stylus.

I know the path is correct, if you give a wrong path, you'll get a build error, in my case the script doesn't crash, he just write into my app.css the import line :

I can now read this in my app.css
@import './../../node_modules/bootstrap-daterangepicker/daterangepicker-bs3.css';

Where the stylus files from my own library can be imported (i had no other choices to use stylus)

I am using gulp-stylus v1.3.3

I also noticed import problem when using simple quotes instead of double quote, but I don't remember why and when.

**Comment by nongrata88** [comment]
> 'include css': true

Stevelacy, thanks for your comment, that worked fine. 
Jenius, totally agree with you.

**Comment by pruett** [comment]
what a wild key name

**Comment by stevelacy** [comment]
@pruett Nothing I can control, it is all stylus.

**Comment by pruett** [comment]
@stevelacy o, i'm fully aware! :smile: i'm glad i found this thread because i didn't find it in the stylus docs :+1:

**Comment by kopax** [comment]
@stevelacy I agree that it is all stylus. I've noticed you are more present than the stylus team.

You could just add an example into the readme.md, it's more a question to share the information and help people not waste their time.

**Comment by stevelacy** [comment]
Thanks, I do have a link to the accord docs, it should have an example of the 'include css' "feature".

If not I'll add one her

**Comment by hanifbbz** [comment]
thanks for the answer (mentioning 'include css' instead of 'includeCss' or 'include-css'). It saved my day. I wish the [JS API page](https://learnboost.github.io/stylus/docs/js.html) points to this convention with some examples. Specially this particular option is very handy.

**Comment by stevelacy** [comment]
I might just send stylus a PR to add notes for that API option, I am sure that there are more confused developers than just us.

**Comment by mystrdat** [comment]
Maybe hyphenate the `include css` key?

**Comment by hanifbbz** [comment]
+1

**Comment by CTimmerman** [comment]
Not sure if it's the same bug, but I had to do this: @import "http://fonts.googleapis.com/css?family=Roboto:300,400,500,700&.css"

**Comment by Venegrad** [comment]
Thanks so much ^)
