### ISSUE TITLE
Error when resolving @require

### ISSUE THREAD

**Issue by simonsmith** [stevelacy/gulp-stylus#99]
I'm having problems with `@require` when trying to compile Stylus files. 

Two files:

**base.styl**
``` css
@require "vars"

html
  color green
  font-size (font-size-base / 16)rem
```

**vars.styl**
``` css
font-size-base = 14
```

This is the error I get:

```
1| @require "vars"
   2|
   3| html
   4|   color green
   5|   font-size (font-size-base / 16)rem
------------------------------------^
   6|

cannot perform font-size-base / 16
    at "html" (/Users/simonsmith/Sites/stylus-bug/styl/base/base.styl:2:16)
```

It seems as though the `font-size-base` var is not picked up from the `vars.styl`. The odd thing is that this only occurs using `gulp watch` and only the second time the file is changed and watch is triggered. It doesn't seem to occur if run gulp manually.

Out of interest I added a `console.log` of `file.contents.toString('utf8')` in the `index.js` and on the first run I get:

```
@require "vars"

html
  color green
  font-size (font-size-base / 16)rem

font-size-base = 14
```

On subsequent compiles I see:

```
@require "vars"

html
  color green
  font-size (font-size-base / 16)rem
```

To debug further I manually set the version of Stylus used with `npm shrinkwrap` and have found that if I use `0.48.1` of Stylus this error does not occur. I'm unsure where the issues lies here, but felt it might be gulp related.

I have an example of this issue in a repo - https://github.com/simonsmith/stylus-bug

**Comment by contra** [comment]
Also having the same issue - super annoying because it effectively breaks mixins

**Comment by stevelacy** [comment]
@simonsmith can you update to gulp-stylus@2.0.0 and stylus@0.49.3 and run the gulp test again?
It is compiling correctly for me:

```css
html {
  color: #008000;
  font-size: 0.875rem;
}

```

**Comment by simonsmith** [comment]
@stevelacy Updated and pushed.

Still seeing the issue here. 

``` bash
$ npm list | grep stylus
stylus-bug@1.0.0 /Users/simonsmith/Sites/stylus-bug
└─┬ gulp-stylus@2.0.0
  ├─┬ stylus@0.49.3
```
The steps are I am following:

1. Run `gulp watch`
1. Make whitespace change to `base.styl` and save (Compile works)
1. Make whitespace change again to `base.styl` (Compile fails)

It then continues to fail for subsequent compiles. What did you try?

**Comment by stevelacy** [comment]
Ah, I was only testing on the initial build, not the subsequent builds.

I added a pure stylus function to your repo: https://github.com/stevelacy/stylus-bug-99

Opening an issue on stylus

**Comment by stevelacy** [comment]
@simonsmith @jenius https://github.com/LearnBoost/stylus/issues/1832#issuecomment-72994474

Next stylus release :)

**Comment by simonsmith** [comment]
@stevelacy Thanks Steve! Really appreciate your time submitting that error report.

I'll close this off!

**Comment by jenius** [comment]
Nice work! :tada:

**Comment by stevelacy** [comment]
Just confirmed, updating works perfectly: https://github.com/stevelacy/stylus-bug-99/commit/9f4a9aca0d2879ddac83e4a8aaa62f56d5a08875

:tada:

**Comment by simonsmith** [comment]
Nice!
